# Generated by Django 6.0.7 on 2026-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reputation",
            field=models.IntegerField(default=0),
        ),
    ]
