# Generated by Django 6.0.7 on 2026-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="steam_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="steam_profile_status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="steam_sync_status",
            field=models.CharField(default="not_synced", max_length=20),
        ),
    ]
