# Generated by Django 6.0.7 on 2026-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_steam_last_sync_user_steam_profile_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="steam_profile_status",
            new_name="steam_library_status",
        ),
    ]
