# Generated by Django 6.0.7 on 2026-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_steam_profile_status_user_steam_library_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="steam_last_update_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
