# Generated by Django 6.0.7 on 2026-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_steam_last_update_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="steam_sync_progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
