# Generated by Django 6.0.7 on 2026-07-31 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_collections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecollection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectiongame",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_games",
                to="game_collections.gamecollection",
            ),
        ),
        migrations.AddField(
            model_name="recommendationvote",
            name="collection_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="game_collections.collectiongame",
            ),
        ),
        migrations.AddField(
            model_name="recommendationvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="collectiongame",
            constraint=models.UniqueConstraint(
                fields=("collection", "game"), name="unique_game_in_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationvote",
            constraint=models.UniqueConstraint(
                fields=("user", "collection_game"), name="unique_recommendation_vote"
            ),
        ),
    ]
