# Generated by Django 6.0.7 on 2026-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_collections", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectiongame",
            name="rating",
        ),
        migrations.AddField(
            model_name="collectiongame",
            name="author_rating",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Author rating of this game in collection (1-5)"
            ),
        ),
    ]
