# Generated by Django 6.0.7 on 2026-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="steam_negative_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="steam_positive_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="steam_review_score",
            field=models.PositiveIntegerField(
                default=0, help_text="Steam review score percentage"
            ),
        ),
    ]
